# Site settings
title: 
header-img: img/home-bg.png
email: paularamirez0316@gmail.com
copyright_name: PRbsas
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: PRbsas
github_username:  PRbsas
learn_profile: PRbsas
email_username: paularamirez0316@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
